In [79]:
import pandas as pd
import numpy as np

In [80]:
data = pd.DataFrame(
    {
        "Price": [100, 120, 130, 140, 167],
        "Dividend": [0, 10, 10, 10, 10],
    },
    index=["31 Dec 2012", "31 Dec 2013", "31 Dec 2014", "31 Dec 2015", "31 Dec 2016"]
)
data.index.name = "Year"

In [81]:
data.head()

             Price  Dividend
Year
31 Dec 2012    100         0
31 Dec 2013    120        10
31 Dec 2014    130        10
31 Dec 2015    140        10
31 Dec 2016    167        10

Given the data in the following table, calculate the returns for each year
on a single share in a company that is purchased on 31 December 2012
for a price of 100 pence and then held for four years. Next, calculate
the total return over the whole period and the annualised average

The return is calculated as $rt = \frac{(P_t - P_{t-1}) + D_t}{P_{t-1}}$.

Total Return is calculated as 
$R_{total} = \frac{(P_n - P_o) + \sum Dt}{p_o}$

Geometric mean / annualised return calculated as $R_{annualised} = (1 + R_{total})^{\frac{1}{n}} -1$

for simple arithmetic return which does not account for compounding we use $\sum_{t=1}^{n} r_t$

The arithmetic mean treats each year independently. The geometric mean asks: what rate, compounded, explains the actual outcome? When returns vary year to year, the geometric mean is always lower than the arithmetic mean. The bigger the variation, the bigger the gap.

In [94]:
data["Capital Gain"] = data["Price"].diff()
data["Total Return"] = data["Capital Gain"] + data["Dividend"]
data["Annual Return"] = data["Total Return"] / data["Price"].shift(1)

In [95]:
data.head()

             Price  Dividend  Capital Gain  Total Return  Annual Return
Year
31 Dec 2012    100         0           NaN           NaN            NaN
31 Dec 2013    120        10          20.0          30.0       0.300000
31 Dec 2014    130        10          10.0          20.0       0.166667
31 Dec 2015    140        10          10.0          20.0       0.153846
31 Dec 2016    167        10          27.0          37.0       0.264286

In [98]:
total_return = data["Total Return"].sum() / data["Price"].iloc[0]
print(f"total_return = {total_return:.2%}")

total_return = 107.00%

In [92]:
annualized_return = (1 + total_return) ** ( 1 / (len(data)- 1 )) - 1
print(f"annualized_return = {annualized_return:.2%}")

annualized_return = 19.95%