In [35]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv("../House Price and index.csv")
df.head()

   Year  Nominal house prices  CPI (2009 levels)
0  2006                 83450               97.6
1  2007                 93231               98.0
2  2008                117905               98.7
3  2009                134806              100.0
4  2010                151757              101.3

2009 is the base year so CPI = 100 there. You're expressing every price as if it were in 2009 money.

In [38]:
df["House Prices  (2009 Levels)"] = round((df["Nominal house prices"]/df["CPI (2009 levels)"] ) * 100)
df.head()

   Year  Nominal house prices  CPI (2009 levels)  House Prices  (2009 Levels)
0  2006                 83450               97.6                      85502.0
1  2007                 93231               98.0                      95134.0
2  2008                117905               98.7                     119458.0
3  2009                134806              100.0                     134806.0
4  2010                151757              101.3                     149809.0

Same idea, but now 2018 is the reference year instead of 2009. You divide by the 2018 CPI value (123.6) instead of 100:

In [45]:
cpi_2018 = 123.6
df["House Prices  (2018 Levels)"] = round((df["Nominal house prices"] / df["CPI (2009 levels)"]  ) * cpi_2018)
df

,Year,Nominal house prices,CPI (2009 levels),House Prices (2009 Levels),House Prices (2018 Levels)
0,2006,83450,97.6,85502.0,105681.0
1,2007,93231,98.0,95134.0,117585.0
2,2008,117905,98.7,119458.0,147650.0
3,2009,134806,100.0,134806.0,166620.0
4,2010,151757,101.3,149809.0,185165.0
5,2011,158478,102.1,155218.0,191850.0
6,2012,173225,106.6,162500.0,200850.0
7,2013,180473,109.4,164966.0,203898.0
8,2014,150501,112.3,134017.0,165645.0
9,2015,163481,116.7,140087.0,173147.0
10,2016,161211,119.2,135244.0,167162.0
11,2017,162228,121.1,133962.0,165577.0
12,2018,162245,123.6,131266.0,162245.0